language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y build-essential python-dev autotools-dev libicu-dev libbz2-dev g++-4.4 g++-4.4-multilib geomview libcurl4-openssl-dev
- cd ACv2_Server
script: make
