language: cpp
sudo: required
dist: trusty
compiler:
- g++
os:
- linux
before_install:
- sudo apt-get -qq update
- sudo apt-get install -y build-essential g++-4.4-multilib
- cd ACv2_Server
script: make -j8
